Repository blusip/blu, pull requests merged in 2023-07, with the labels that each got.

#1 File hierarchy restructuing
  .gitignore
  go.work
  internal/sip/parser.go
  internal/sip/parser/parser_test.go
  internal/sip/request.go
  internal/sip/response.go
  pkg/parser/go.mod
Labels: formatting

#2 SIP parser (incomplete), basic internal infrastructure
  .gitignore
  go.mod
  go.sum
  internal/header/headers.go
  internal/sip/methods.go
  internal/sip/parser.go
  internal/sip/parser/hexconv.go
  internal/sip/parser/parser.go
  internal/sip/parser/parser_test.go
  internal/sip/parser/states.go
  internal/sip/request.go
  internal/sip/status/codes.go
  settings/settings.go
Labels: enhancement

#4 Add status code & errors types
  internal/sip/parser/parser.go
  internal/sip/status/codes.go
  internal/sip/status/errors.go
Labels: formatting

#5 reformatted codes and errors
  internal/sip/status/codes.go
  internal/sip/status/errors.go
Labels: formatting

#6 Finished SIP parser
  internal/sip/parser/parser.go
  internal/sip/parser/parser_test.go
  internal/sip/parser/states.go
  internal/sip/request.go
  settings/default.go
  settings/settings.go
Labels: enhancement

#21 Update formatting.yml
  .github/workflows/formatting.yml
Labels: CI/CD

#17 Basic SDP parser
  go.mod
  internal/sdp/description.go
  internal/sdp/errors.go
  internal/sdp/parser.go
  internal/sdp/parser_test.go
  internal/sdp/parserbench_test.go
  internal/sdp/values.go
  internal/sip/codes.go
  internal/sip/errors.go
  internal/sip/hexconv.go
  internal/sip/parser.go
  internal/sip/parser/parser.go
  internal/sip/parser_test.go
  internal/sip/response.go
  internal/sip/states.go
Labels: enhancement, formatting

#22 Update formatting.yml
  .github/workflows/formatting.yml
Labels: CI/CD
